name = "zegatz"
pages_build_output_dir = "./dist"
compatibility_date = "2024-05-04"
compatibility_flags = ["nodejs_compat"]


[vars]
NOTION_TOKEN = "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"
NOTION_DATABASE_ID = "1da3cfd6574e804aaec9ec7865b7e4a8"